"""change new model

Revision ID: a49b5ecbf750
Revises: 2c5a00699ec7
Create Date: 2020-06-04 00:30:06.976124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a49b5ecbf750'
down_revision = '2c5a00699ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author', sa.String(length=50), nullable=True))
    op.add_column('news', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_news_timestamp'), 'news', ['timestamp'], unique=False)
    op.drop_column('news', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_news_timestamp'), table_name='news')
    op.drop_column('news', 'timestamp')
    op.drop_column('news', 'body')
    op.drop_column('news', 'author')
    # ### end Alembic commands ###
