"""add post html column

Revision ID: ebdbc01ac758
Revises: a49b5ecbf750
Create Date: 2020-06-05 09:34:23.623531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdbc01ac758'
down_revision = 'a49b5ecbf750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'html')
    # ### end Alembic commands ###
